package br.com.angatusistemas.lib.criptografy;

import org.mindrot.jbcrypt.BCrypt;

import br.com.angatusistemas.lib.console.Console;

/**
 * [PT] Classe utilitária para criptografia e verificação de senhas utilizando o algoritmo BCrypt.
 * <p>
 * O BCrypt é um algoritmo de hash adaptativo, considerado seguro contra ataques de força bruta,
 * pois permite ajustar o custo computacional (fator de trabalho). Esta classe utiliza o salt
 * gerado automaticamente por {@link BCrypt#gensalt()}.
 * </p>
 * <p>
 * <b>Características:</b>
 * <ul>
 *   <li>Gera hash de senha com salt embutido (formato: $2a$ / $2b$ / $2y$ + custo + hash de 53 caracteres)</li>
 *   <li>Verificação segura contra timing attacks através de {@link BCrypt#checkpw(String, String)}</li>
 *   <li>Método {@link #criptography(String)} aceita hashes já gerados (não re-criptografa)</li>
 * </ul>
 * </p>
 * <p>
 * Exemplo de uso:
 * <pre>
 * // Criptografar senha
 * String hash = Password.criptography("minhaSenha123");
 *
 * // Verificar senha
 * if (Password.checkCriptography("minhaSenha123", hash)) {
 *     System.out.println("Senha correta");
 * }
 * </pre>
 * </p>
 *
 * [EN] Utility class for password hashing and verification using the BCrypt algorithm.
 * <p>
 * BCrypt is an adaptive hash algorithm, considered secure against brute force attacks
 * because it allows adjusting the computational cost (work factor). This class uses the
 * salt automatically generated by {@link BCrypt#gensalt()}.
 * </p>
 * <p>
 * <b>Features:</b>
 * <ul>
 *   <li>Generates password hash with embedded salt (format: $2a$ / $2b$ / $2y$ + cost + 53‑char hash)</li>
 *   <li>Secure verification against timing attacks via {@link BCrypt#checkpw(String, String)}</li>
 *   <li>{@link #criptography(String)} accepts already hashed passwords (does not re‑hash)</li>
 * </ul>
 * </p>
 * <p>
 * Usage example:
 * <pre>
 * // Hash a password
 * String hash = Password.criptography("myPassword123");
 *
 * // Verify password
 * if (Password.checkCriptography("myPassword123", hash)) {
 *     System.out.println("Password correct");
 * }
 * </pre>
 * </p>
 *
 * @author [Sua equipe]
 * @see BCrypt
 */
public final class Password {

    private Password() {
        throw new UnsupportedOperationException("Utility class cannot be instantiated");
    }

    /**
     * [PT] Criptografa uma senha usando BCrypt.
     * <p>
     * Se a senha informada já estiver no formato de um hash BCrypt válido (ex: começando com $2a$, $2b$ ou $2y$),
     * o valor é retornado sem modificação. Caso contrário, gera um novo hash com salt automático.
     * </p>
     * <p>
     * <b>Nota:</b> O método não aceita senhas nulas. Em caso de {@code null}, retorna {@code null}
     * e registra um aviso no log.
     * </p>
     *
     * [EN] Hashes a password using BCrypt.
     * <p>
     * If the provided password is already a valid BCrypt hash (starts with $2a$, $2b$ or $2y$),
     * the value is returned unchanged. Otherwise, generates a new hash with automatic salt.
     * </p>
     * <p>
     * <b>Note:</b> This method does not accept null passwords. If {@code null} is passed, returns {@code null}
     * and logs a warning.
     * </p>
     *
     * @param password [PT] senha em texto puro (não nula, não vazia recomendado)
     *                 [EN] plain text password (non‑null, non‑empty recommended)
     * @return [PT] hash BCrypt da senha, ou {@code null} se a entrada for nula
     *         [EN] BCrypt hash of the password, or {@code null} if input is null
     */
    public static String criptography(String password) {
        if (password == null) {
            Console.warn("Password.criptography: entrada nula retornará null");
            return null;
        }
        if (isBCryptHash(password)) {
            Console.debug("Password.criptography: valor já é um hash BCrypt, retornando original");
            return password;
        }
        String hash = BCrypt.hashpw(password, BCrypt.gensalt());
        Console.debug("Password.criptography: novo hash gerado");
        return hash;
    }

    /**
     * [PT] Verifica se uma senha em texto puro corresponde a um hash BCrypt previamente gerado.
     * <p>
     * O método é seguro contra timing attacks (implementação do BCrypt). Retorna {@code true}
     * apenas se a senha fornecida, quando criptografada com o mesmo salt do hash, produzir
     * o mesmo valor.
     * </p>
     * <p>
     * Parâmetros nulos ou hash inválido resultam em {@code false}.
     * </p>
     *
     * [EN] Checks whether a plain text password matches a previously generated BCrypt hash.
     * <p>
     * The method is secure against timing attacks (BCrypt implementation). Returns {@code true}
     * only if the given password, when hashed with the same salt as the stored hash, produces
     * the same value.
     * </p>
     * <p>
     * Null parameters or an invalid hash result in {@code false}.
     * </p>
     *
     * @param password              [PT] senha em texto puro
     *                              [EN] plain text password
     * @param criptographedPassword [PT] hash BCrypt previamente armazenado
     *                              [EN] previously stored BCrypt hash
     * @return [PT] {@code true} se a senha corresponde ao hash, {@code false} caso contrário
     *         [EN] {@code true} if the password matches the hash, {@code false} otherwise
     */
    public static boolean checkCriptography(String password, String criptographedPassword) {
        if (password == null || criptographedPassword == null) {
            Console.debug("Password.checkCriptography: um dos parâmetros é nulo, retornando false");
            return false;
        }
        try {
            boolean result = BCrypt.checkpw(password, criptographedPassword);
            Console.debug("Password.checkCriptography: verificação concluída, resultado=%s", result);
            return result;
        } catch (Exception e) {
            Console.error("Password.checkCriptography: erro ao verificar hash", e);
            return false;
        }
    }

    /**
     * [PT] Verifica se uma string tem o formato de um hash BCrypt válido.
     * <p>
     * O formato esperado é: {@code $2[aby]$dd$salt+hash} onde:
     * <ul>
     *   <li>{@code $2a$}, {@code $2b$} ou {@code $2y$} indica o tipo do hash</li>
     *   <li>{@code dd} é o custo (dois dígitos, ex: 10)</li>
     *   <li>seguido de 53 caracteres no conjunto {@code [./A-Za-z0-9]}</li>
     * </ul>
     * </p>
     * <p>
     * Este método é usado internamente para evitar re‑hash de valores já criptografados.
     * </p>
     *
     * [EN] Checks whether a string has the format of a valid BCrypt hash.
     * <p>
     * The expected format is: {@code $2[aby]$dd$salt+hash} where:
     * <ul>
     *   <li>{@code $2a$}, {@code $2b$} or {@code $2y$} indicates the hash type</li>
     *   <li>{@code dd} is the cost (two digits, e.g., 10)</li>
     *   <li>followed by 53 characters from the set {@code [./A-Za-z0-9]}</li>
     * </ul>
     * </p>
     * <p>
     * This method is used internally to prevent re‑hashing of already hashed values.
     * </p>
     *
     * @param value [PT] string a ser testada (pode ser {@code null})
     *              [EN] string to test (may be {@code null})
     * @return [PT] {@code true} se a string tem formato de hash BCrypt, {@code false} caso contrário
     *         [EN] {@code true} if the string matches a BCrypt hash format, {@code false} otherwise
     */
    private static boolean isBCryptHash(String value) {
        if (value == null) return false;
        // Regex aceita $2a$, $2b$ ou $2y$ + custo de 2 dígitos + 53 caracteres permitidos
        return value.matches("^\\$2[aby]\\$\\d{2}\\$[./A-Za-z0-9]{53}$");
    }
}